# Generated by Django 5.1.15 on 2026-08-07 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='controlevidence',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_links', to='documents.document'),
        ),
        migrations.AddField(
            model_name='controlevidence',
            name='linked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_links_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlmapping',
            name='controls',
            field=models.ManyToManyField(related_name='mappings', to='compliance.control'),
        ),
        migrations.AddField(
            model_name='controlcategory',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='compliance.framework'),
        ),
        migrations.AlterUniqueTogether(
            name='control',
            unique_together={('category', 'control_id')},
        ),
        migrations.AlterUniqueTogether(
            name='controlevidence',
            unique_together={('control', 'document')},
        ),
        migrations.AlterUniqueTogether(
            name='controlcategory',
            unique_together={('framework', 'key')},
        ),
    ]
