# Generated by Django 5.2.17 on 2026-09-04 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='last_tested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controls_tested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='control',
            name='last_tested_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='last_tested_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='test_interval_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How often this control should be retested. Blank uses the site default.', null=True),
        ),
    ]
