# Generated by Django 5.2.17 on 2026-09-04 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_vendors_and_responsibilities'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsibility',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities', to='vendors.vendor'),
        ),
        migrations.AddConstraint(
            model_name='responsibility',
            constraint=models.UniqueConstraint(fields=('control', 'user', 'role'), name='uniq_resp_user_role'),
        ),
        migrations.AddConstraint(
            model_name='responsibility',
            constraint=models.UniqueConstraint(fields=('control', 'vendor', 'role'), name='uniq_resp_vendor_role'),
        ),
        migrations.AddConstraint(
            model_name='responsibility',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('vendor__isnull', True)), models.Q(('user__isnull', True), ('vendor__isnull', False)), _connector='OR'), name='resp_exactly_one_party'),
        ),
    ]
