# Generated by Django 5.2.17 on 2026-09-05 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sso_assertion'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAuthnChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('challenge', models.CharField(max_length=64)),
                ('purpose', models.CharField(choices=[('register', 'Enrol a passkey'), ('login', 'Sign in')], max_length=12)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_challenges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebAuthnCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('credential_id', models.CharField(max_length=1400, unique=True)),
                ('public_key', models.BinaryField()),
                ('algorithm', models.SmallIntegerField(help_text='COSE algorithm identifier.')),
                ('sign_count', models.PositiveBigIntegerField(default=0)),
                ('aaguid', models.CharField(blank=True, max_length=36)),
                ('transports', models.JSONField(blank=True, default=list)),
                ('backup_eligible', models.BooleanField(default=False)),
                ('backup_state', models.BooleanField(default=False)),
                ('user_verified', models.BooleanField(default=False, help_text='The authenticator verified the person (PIN/biometric) at enrolment.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('suspect_at', models.DateTimeField(blank=True, null=True)),
                ('suspect_reason', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passkeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
