# Generated by Django 5.2.17 on 2026-09-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_backup_codes_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='digest',
            field=models.CharField(choices=[('off', 'Off'), ('daily', 'Daily'), ('weekly', 'Weekly (Monday)')], default='off', max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='digest_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
