# Generated by Django 5.2.17 on 2026-09-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_workspaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfadevice',
            name='last_counter',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workspace',
            name='notification_email',
            field=models.EmailField(blank=True, help_text="Where this organisation's reminders and alerts go. Blank falls back to the installation's COMPLIANCE_TEAM_EMAIL.", max_length=254),
        ),
    ]
