# Generated by Django 5.2.17 on 2026-09-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_encrypt_webhooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sessions_valid_from',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
