# Generated by Django 5.2.17 on 2026-09-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=40)),
                ('channel', models.CharField(max_length=10)),
                ('ok', models.BooleanField(default=False)),
                ('response_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name_plural': 'webhook deliveries',
                'ordering': ['-created_at'],
            },
        ),
    ]
