# Generated by Django 5.2.17 on 2026-09-05 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='packagecontrol',
            name='population_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packagecontrol',
            name='population_source',
            field=models.CharField(blank=True, help_text="Where the population came from, e.g. 'HR termination report, FY26'.", max_length=255),
        ),
        migrations.AddField(
            model_name='packagecontrol',
            name='sampling_method',
            field=models.CharField(blank=True, choices=[('random', 'Random'), ('haphazard', 'Haphazard'), ('judgmental', 'Judgmental'), ('complete', 'Complete population')], max_length=12),
        ),
        migrations.AddField(
            model_name='packagecontrol',
            name='sampling_note',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='PackageSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField(default=0)),
                ('identifier', models.CharField(help_text='The item sampled: a ticket, a user, a change number, a date.', max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('population_ref', models.CharField(blank=True, help_text="Where this item sits in the population, e.g. 'row 17 of the export'.", max_length=255)),
                ('evidence_name', models.CharField(blank=True, max_length=255)),
                ('sealed_in', models.BooleanField(default=False)),
                ('selected_by_name', models.CharField(blank=True, max_length=200)),
                ('selected_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(choices=[('pending', 'Not yet tested'), ('pass', 'Pass'), ('fail', 'Exception'), ('not_tested', 'Not tested')], default='pending', max_length=12)),
                ('exception_note', models.TextField(blank=True)),
                ('tested_by_name', models.CharField(blank=True, max_length=200)),
                ('tested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='attestations.packageevidence')),
                ('package_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='attestations.packagecontrol')),
                ('selected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples_selected', to=settings.AUTH_USER_MODEL)),
                ('tested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples_tested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ordinal', 'identifier', 'pk'],
                'unique_together': {('package_control', 'identifier')},
            },
        ),
    ]
