# Generated by Django 5.2.17 on 2026-09-05 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestations', '0002_package_samples'),
        ('documents', '0002_folder_name_validator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PbcRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('reference', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('control_ref', models.CharField(blank=True, max_length=40)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High')], default='normal', max_length=8)),
                ('status', models.CharField(choices=[('open', 'Open'), ('provided', 'Provided'), ('accepted', 'Accepted'), ('returned', 'Returned'), ('withdrawn', 'Withdrawn')], default='open', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('assignee_name', models.CharField(blank=True, max_length=200)),
                ('requested_by_name', models.CharField(blank=True, max_length=200)),
                ('requested_by_side', models.CharField(choices=[('auditor', 'Auditor'), ('organisation', 'Organisation')], default='organisation', max_length=12)),
                ('response_note', models.TextField(blank=True)),
                ('provided_by_name', models.CharField(blank=True, max_length=200)),
                ('provided_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by_name', models.CharField(blank=True, max_length=200)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('returned_note', models.TextField(blank=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('reminders_sent', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pbc_requests_accepted', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pbc_requests_assigned', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pbc_requests', to='attestations.evidencepackage')),
                ('package_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pbc_requests', to='attestations.packagecontrol')),
                ('provided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pbc_requests_provided', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pbc_requests_raised', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['package', 'ordinal'],
                'unique_together': {('package', 'ordinal')},
            },
        ),
        migrations.CreateModel(
            name='PbcItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('content_sha256', models.CharField(blank=True, max_length=64)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('attached_by_name', models.CharField(blank=True, max_length=200)),
                ('attached_at', models.DateTimeField(auto_now_add=True)),
                ('attached_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pbc_items_attached', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pbc_items', to='documents.document')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='attestations.pbcrequest')),
            ],
            options={
                'ordering': ['attached_at', 'pk'],
                'unique_together': {('request', 'document')},
            },
        ),
    ]
