# Generated by Django 5.2.17 on 2026-09-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestations', '0003_pbc_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigningKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(max_length=16, unique=True)),
                ('public_key', models.CharField(help_text='Raw Ed25519 public key, base64.', max_length=64)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='evidencepackage',
            name='manifest_signature',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='evidencepackage',
            name='signing_key_id',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
        migrations.AddField(
            model_name='evidencepackage',
            name='signing_public_key',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
