# Generated by Django 5.2.17 on 2026-09-07 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_workspaces'),
        ('attestations', '0005_workspaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='signingkey',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signing_keys', to='accounts.workspace'),
        ),
    ]
