# Generated by Django 5.2.17 on 2026-09-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadinessSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_controls', models.PositiveIntegerField(default=0)),
                ('applicable', models.PositiveIntegerField(default=0)),
                ('implemented', models.PositiveIntegerField(default=0)),
                ('in_progress', models.PositiveIntegerField(default=0)),
                ('with_evidence', models.PositiveIntegerField(default=0)),
                ('evidence_links', models.PositiveIntegerField(default=0)),
                ('documents_overdue', models.PositiveIntegerField(default=0)),
                ('risks_open', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
