"""Document-management API: folders, permissions, documents, reviews, templates."""
from django.utils import timezone
from rest_framework import status, viewsets
from rest_framework.decorators import action
from rest_framework.exceptions import PermissionDenied, ValidationError
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from accounts.permissions import CanManageDocuments
from audit.events import record_evidence_read
from .models import (
    Document,
    DocumentVersion,
    Folder,
    FolderPermission,
    FormTemplate,
)
from .access import accessible_folder_ids
from . import monitor
from .downloads import serve_inline, serve_stored_file
from . import preview as preview_lib
from .scanning import scan_or_raise
from .permissions import DocumentAccessPermission, FolderAccessPermission
from .serializers import (
    DocumentSerializer,
    DocumentVersionSerializer,
    FolderPermissionSerializer,
    FolderSerializer,
    FormTemplateSerializer,
)
from .uploads import validate_upload


def _visible_folders(user):
    """Folders the user may at least view (permission inheritance resolved efficiently)."""
    ids = accessible_folder_ids(user)
    return list(
        Folder.objects.filter(id__in=ids).select_related("owner", "control", "parent")
    )


class FolderViewSet(viewsets.ModelViewSet):
    serializer_class = FolderSerializer
    permission_classes = [IsAuthenticated, FolderAccessPermission]
    filterset_fields = ["parent", "control", "is_framework_root"]
    search_fields = ["name"]

    def get_queryset(self):
        ids = accessible_folder_ids(self.request.user)
        return Folder.objects.filter(id__in=ids).select_related("owner", "control", "parent")

    def perform_create(self, serializer):
        user = self.request.user
        parent = serializer.validated_data.get("parent")
        allowed = user.can_manage_folders or (parent and parent.can_edit(user))
        if not allowed:
            raise PermissionDenied("You cannot create a folder here.")
        serializer.save()

    def perform_update(self, serializer):
        """Re-parenting is a structural change: it exposes the moved subtree
        to everyone with grants on the destination's ancestors. It therefore
        requires *manage* on the folder being moved and *edit* on the
        destination — matching the folder-permission rules."""
        folder = serializer.instance
        user = self.request.user
        new_parent = serializer.validated_data.get("parent", folder.parent)
        if (new_parent.id if new_parent else None) != folder.parent_id:
            if folder.is_seeded:
                raise PermissionDenied("Framework folders are generated from the control library and cannot be moved.")
            if not folder.can_manage(user):
                raise PermissionDenied("You need manage access on a folder to move it.")
            if new_parent is not None and not new_parent.can_edit(user):
                raise PermissionDenied("You need edit access on the destination folder.")
            if new_parent is None and not user.can_manage_folders:
                raise PermissionDenied("Only folder managers can create top-level folders.")
        if "name" in serializer.validated_data and folder.is_seeded \
                and serializer.validated_data["name"] != folder.name:
            raise PermissionDenied("Framework folders are named from the control library and cannot be renamed.")
        # The owner IS a manager (Folder.can_manage), so handing ownership to
        # yourself with only edit access would be a self-service promotion.
        new_owner = serializer.validated_data.get("owner", folder.owner)
        if (new_owner.id if new_owner else None) != folder.owner_id and not folder.can_manage(user):
            raise PermissionDenied("You need manage access on a folder to change its owner.")
        serializer.save()

    def perform_destroy(self, instance):
        # The generated framework/category/control folders are the spine the
        # evidence tree hangs from; deleting one cascades every document and
        # grant beneath it. They are regenerated by seed_frameworks, so there
        # is never a reason to remove them through the API.
        if instance.is_seeded:
            raise PermissionDenied("Framework folders cannot be deleted.")
        instance.delete()

    @action(detail=False, methods=["get"])
    def tree(self, request):
        """Return the folder hierarchy the user can see, as nested nodes."""
        folders = _visible_folders(request.user)
        # A user granted access on a mid-tree folder cannot see its ancestors,
        # so bucketing strictly by parent_id would leave their folders orphaned
        # under a parent key that is never rendered — an empty tree. Treat any
        # folder whose parent is not itself visible as a root of this user's view.
        visible_ids = {f.id for f in folders}
        by_parent = {}
        for f in folders:
            key = f.parent_id if f.parent_id in visible_ids else None
            by_parent.setdefault(key, []).append(f)

        def build(parent_id):
            nodes = []
            for f in sorted(by_parent.get(parent_id, []), key=lambda x: x.name):
                nodes.append({
                    "id": f.id, "name": f.name, "control": f.control_id,
                    "owner": f.owner.get_full_name() if f.owner else None,
                    "my_access": f.effective_access(request.user),
                    "is_seeded": f.is_seeded,
                    "document_count": f.documents.count(),
                    "children": build(f.id),
                })
            return nodes

        return Response(build(None))

    @action(detail=True, methods=["get"])
    def permissions(self, request, pk=None):
        folder = self.get_object()
        perms = FolderPermission.objects.filter(folder=folder).select_related("role", "user")
        return Response(FolderPermissionSerializer(perms, many=True).data)


class FolderPermissionViewSet(viewsets.ModelViewSet):
    serializer_class = FolderPermissionSerializer
    filterset_fields = ["folder", "role", "user"]

    def get_queryset(self):
        """Only expose grants on folders the caller can manage — the access-control
        map is itself sensitive, so it must not leak past folder permissions."""
        user = self.request.user
        qs = FolderPermission.objects.select_related("folder", "role", "user")
        if user.can_manage_folders or user.can_view_all or user.is_superuser:
            return qs
        manageable = [
            f.id for f in Folder.objects.select_related("parent", "owner")
            if f.can_manage(user)
        ]
        return qs.filter(folder_id__in=manageable)

    def _check_manage(self, folder):
        if not folder.can_manage(self.request.user):
            raise PermissionDenied("You must be able to manage this folder to change its access.")

    def perform_create(self, serializer):
        self._check_manage(serializer.validated_data["folder"])
        serializer.save()

    def perform_update(self, serializer):
        # Guard both the existing folder and any folder the grant is being moved to.
        self._check_manage(serializer.instance.folder)
        target = serializer.validated_data.get("folder")
        if target is not None:
            self._check_manage(target)
        serializer.save()

    def perform_destroy(self, instance):
        self._check_manage(instance.folder)
        instance.delete()


class DocumentViewSet(viewsets.ModelViewSet):
    serializer_class = DocumentSerializer
    permission_classes = [IsAuthenticated, DocumentAccessPermission]
    filterset_fields = ["folder", "status", "owner", "control", "review_cadence"]
    search_fields = ["name", "description"]
    ordering_fields = ["updated_at", "next_review_date", "name"]

    def get_queryset(self):
        visible_ids = accessible_folder_ids(self.request.user)
        return (
            Document.objects.filter(folder_id__in=visible_ids)
            .select_related("folder", "owner", "control")
            .prefetch_related("control_links__control__category__framework")
        )

    def _require_folder_edit(self, folder):
        if not folder.can_edit(self.request.user):
            raise PermissionDenied("You need edit access to this folder.")

    def perform_create(self, serializer):
        folder = serializer.validated_data["folder"]
        self._require_folder_edit(folder)
        # After the permission check, never in validate_file: is_valid() runs
        # before this, so scanning there would hand an unauthorised caller a
        # signature-set oracle and a way to saturate the scanner.
        scan_or_raise(serializer.validated_data.get("file"), self.request)
        doc = serializer.save(
            created_by=self.request.user,
            owner=serializer.validated_data.get("owner") or self.request.user,
        )
        doc.compute_next_review()
        doc.save(update_fields=["next_review_date"])
        monitor.mark_clean(doc)

    def perform_update(self, serializer):
        # Replacing the bytes is what `new_version` is for: it takes edit on
        # the folder, scans the upload, archives the old file and bumps the
        # version. A plain PATCH did none of that and left the stale scan
        # verdict in place, so the field is refused here.
        if "file" in serializer.validated_data:
            raise ValidationError(
                {"file": "Upload a new version instead: POST /documents/{id}/new_version/."})
        # Moving a document via PATCH must also require edit on the destination,
        # matching the dedicated `move` action (otherwise a doc could be planted
        # in a folder the user can't edit).
        new_folder = serializer.validated_data.get("folder")
        if new_folder is not None and new_folder.id != serializer.instance.folder_id:
            self._require_folder_edit(new_folder)
        doc = serializer.save()
        doc.compute_next_review()
        doc.save(update_fields=["next_review_date"])

    # --- actions -----------------------------------------------------------
    @action(detail=True, methods=["post"])
    def rename(self, request, pk=None):
        doc = self.get_object()
        self._require_folder_edit(doc.folder)
        name = (request.data.get("name") or "").strip()
        if not name:
            raise ValidationError({"name": "A new name is required."})
        doc.name = name[:255]
        doc.save(update_fields=["name", "updated_at"])
        return Response(DocumentSerializer(doc, context={"request": request}).data)

    @action(detail=True, methods=["post"])
    def move(self, request, pk=None):
        doc = self.get_object()
        self._require_folder_edit(doc.folder)  # edit on source
        try:
            target = Folder.objects.get(pk=request.data.get("folder"))
        except (Folder.DoesNotExist, TypeError, ValueError):
            raise ValidationError({"folder": "Target folder not found."})
        self._require_folder_edit(target)       # edit on destination
        doc.folder = target
        doc.save(update_fields=["folder", "updated_at"])
        return Response(DocumentSerializer(doc, context={"request": request}).data)

    @action(detail=True, methods=["post"])
    def new_version(self, request, pk=None):
        """Archive the current file and attach a new one, bumping the version."""
        doc = self.get_object()
        self._require_folder_edit(doc.folder)
        new_file = request.FILES.get("file") or request.data.get("file")
        if not new_file or isinstance(new_file, str):
            raise ValidationError({"file": "A file is required."})
        try:
            validate_upload(new_file)
        except ValidationError as exc:
            raise ValidationError({"file": exc.detail})
        scan_or_raise(new_file, request)
        # Never archive quarantined bytes: DocumentVersion is a download route
        # of its own and archived files are not re-scanned, so keeping them
        # would leave the infected copy reachable after the "fix".
        if doc.file and not doc.quarantined_at:
            DocumentVersion.objects.create(
                document=doc, version=doc.version, file=doc.file,
                note=str(request.data.get("note", ""))[:255], uploaded_by=request.user,
            )
        doc.file = new_file
        doc.version += 1
        doc.status = Document.Status.DRAFT
        doc.reminders_sent = []
        # A new file is a new scan subject: clear any quarantine the old
        # version carried, and record the clean result when scanning is on.
        doc.quarantined_at = None
        doc.scan_status = Document.Scan.UNSCANNED
        doc.scan_signature = ""
        doc.save()
        monitor.mark_clean(doc)
        return Response(DocumentSerializer(doc, context={"request": request}).data)

    @action(detail=True, methods=["get"])
    def download(self, request, pk=None):
        """Stream the current file to a caller who may see its folder.

        get_object() has already run get_queryset() (folder-filtered) and
        DocumentAccessPermission, so reaching this line means the read is
        authorised. Recorded in the audit trail: who read which evidence is
        exactly the kind of question this product exists to answer.
        """
        doc = monitor.refuse_if_quarantined(self.get_object())
        record_evidence_read(request, doc)
        return serve_stored_file(doc.file, doc.name)

    @action(detail=True, methods=["get"])
    def preview(self, request, pk=None):
        """Show the document in the browser without rendering it as HTML.

        PDFs and images stream inline after a magic-byte check; Word and Excel
        come back as structured JSON the app renders itself. Same authorisation
        as download, and recorded as a read the same way.
        """
        doc = monitor.refuse_if_quarantined(self.get_object())
        return preview_response(request, doc.file, doc.name, doc)

    @action(detail=True, methods=["get"], url_path=r"versions/(?P<version_pk>[^/.]+)/download")
    def download_version(self, request, pk=None, version_pk=None):
        """Stream an archived version. Same authorisation as the live file."""
        doc = monitor.refuse_if_quarantined(self.get_object())
        try:
            version = doc.versions.get(pk=version_pk)
        except DocumentVersion.DoesNotExist:
            raise ValidationError({"version": "Not found."})
        record_evidence_read(request, doc, version=version.version)
        return serve_stored_file(version.file, f"{doc.name} (v{version.version})")

    @action(detail=True, methods=["get"])
    def versions(self, request, pk=None):
        doc = self.get_object()
        return Response(DocumentVersionSerializer(doc.versions.all(), many=True).data)

    @action(detail=True, methods=["post"])
    def mark_reviewed(self, request, pk=None):
        """Record a completed review: reset the review clock and clear reminders."""
        doc = self.get_object()
        self._require_folder_edit(doc.folder)
        doc.last_reviewed = timezone.now().date()
        doc.status = Document.Status.APPROVED
        doc.reminders_sent = []
        doc.compute_next_review()
        doc.save()
        return Response(DocumentSerializer(doc, context={"request": request}).data)

    @action(detail=False, methods=["get"])
    def reviews(self, request):
        """Upcoming and overdue document reviews (drives the dashboard + calendar)."""
        try:
            horizon = int(request.query_params.get("days", 90))
        except (TypeError, ValueError):
            horizon = 90
        horizon = max(0, min(horizon, 3650))
        today = timezone.now().date()
        docs = [d for d in self.get_queryset().exclude(next_review_date=None)
                if d.next_review_date is not None
                and (d.next_review_date - today).days <= horizon]
        docs.sort(key=lambda d: d.next_review_date)
        return Response(DocumentSerializer(docs, many=True, context={"request": request}).data)


class FormTemplateViewSet(viewsets.ModelViewSet):
    """Central library of reusable blank forms/policy templates."""
    queryset = FormTemplate.objects.all()
    serializer_class = FormTemplateSerializer
    permission_classes = [CanManageDocuments]
    filterset_fields = ["category"]
    search_fields = ["name", "description"]

    def perform_create(self, serializer):
        scan_or_raise(serializer.validated_data.get("file"), self.request)
        serializer.save()

    def perform_update(self, serializer):
        scan_or_raise(serializer.validated_data.get("file"), self.request)
        serializer.save()

    @action(detail=True, methods=["get"])
    def download(self, request, pk=None):
        """Templates are blank forms, not evidence, so this is not audited --
        but it still goes through the API so no storage path is published."""
        return serve_stored_file(self.get_object().file, self.get_object().name)


def preview_response(request, file_field, name, document, version=None):
    """Shared by the document and package-evidence preview endpoints."""
    from rest_framework.exceptions import ValidationError as DRFValidationError

    if not file_field:
        raise DRFValidationError({"detail": "This document has no file."})
    try:
        result = preview_lib.render(file_field, name)
    except preview_lib.PreviewError as exc:
        return Response({"kind": None, "detail": str(exc)}, status=415)
    record_evidence_read(request, document, version=version)
    if result["kind"] == "pdf":
        return serve_inline(file_field, "application/pdf", name)
    if result["kind"] == "image":
        with file_field.open("rb") as fh:
            head = fh.read(16)
        return serve_inline(file_field, preview_lib.image_content_type(head), name)
    return Response(result)
