# Generated by Django 5.2.17 on 2026-09-04 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0004_vendors_and_responsibilities'),
        ('documents', '0002_folder_name_validator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('category', models.CharField(blank=True, help_text='What they do for us: cloud hosting, payroll, identity, security testing…', max_length=80)),
                ('website', models.URLField(blank=True)),
                ('contact_name', models.CharField(blank=True, max_length=160)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('tier', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', help_text='How much we depend on them and how bad a failure would be.', max_length=10)),
                ('status', models.CharField(choices=[('prospective', 'Prospective'), ('active', 'Active'), ('offboarding', 'Offboarding'), ('offboarded', 'Offboarded')], default='active', max_length=12)),
                ('data_handled', models.CharField(blank=True, help_text="What of ours they touch, e.g. 'customer PII, cardholder data'.", max_length=255)),
                ('services', models.TextField(blank=True)),
                ('review_cadence', models.CharField(choices=[('quarterly', 'Quarterly'), ('semiannual', 'Every 6 months'), ('annual', 'Annual'), ('biennial', 'Every 2 years')], default='annual', max_length=12)),
                ('last_reviewed', models.DateField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vendors', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='The relationship owner accountable for this vendor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_vendors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VendorAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('soc2_type1', 'SOC 2 Type I'), ('soc2_type2', 'SOC 2 Type II'), ('iso27001', 'ISO/IEC 27001 certificate'), ('pci_aoc', 'PCI DSS AOC'), ('pentest', 'Penetration test'), ('questionnaire', 'Security questionnaire'), ('dpa', 'Data-processing agreement'), ('contract', 'Contract / MSA'), ('resp_matrix', 'Responsibility matrix (their document)'), ('other', 'Other')], max_length=16)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, help_text='When this stops being acceptable evidence.', null=True)),
                ('result', models.CharField(choices=[('satisfactory', 'Satisfactory'), ('exceptions', 'Exceptions noted'), ('unsatisfactory', 'Unsatisfactory'), ('pending', 'Pending review')], default='pending', max_length=16)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('findings', models.TextField(blank=True, help_text='Exceptions, CUECs, anything to follow up.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_assessments', to='documents.document')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_assessments_reviewed', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-issued_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedResponsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsibility', models.CharField(choices=[('provider', 'Provider'), ('customer', 'Customer (us)'), ('shared', 'Shared'), ('not_applicable', 'Not applicable')], max_length=16)),
                ('provider_statement', models.TextField(blank=True, help_text='What the provider does for this control.')),
                ('customer_statement', models.TextField(blank=True, help_text='What remains ours to do (CUECs, configuration, monitoring).')),
                ('source', models.CharField(default='manual', help_text='manual | import -- how this row came to exist.', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_responsibilities', to='compliance.control')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_responsibilities_edited', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_responsibilities', to='vendors.vendor')),
            ],
            options={
                'verbose_name_plural': 'shared responsibilities',
                'ordering': ['control'],
                'unique_together': {('vendor', 'control')},
            },
        ),
    ]
