# Generated by Django 5.2.17 on 2026-09-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='matrix_layout',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorassessment',
            name='bridge_reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorassessment',
            name='kind',
            field=models.CharField(choices=[('soc2_type1', 'SOC 2 Type I'), ('soc2_type2', 'SOC 2 Type II'), ('iso27001', 'ISO/IEC 27001 certificate'), ('pci_aoc', 'PCI DSS AOC'), ('pentest', 'Penetration test'), ('questionnaire', 'Security questionnaire'), ('dpa', 'Data-processing agreement'), ('contract', 'Contract / MSA'), ('resp_matrix', 'Responsibility matrix (their document)'), ('bridge_letter', 'Bridge letter'), ('other', 'Other')], max_length=16),
        ),
    ]
