# Generated by Django 5.2.17 on 2026-09-03 01:25

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=255, validators=[documents.models.validate_folder_name]),
        ),
    ]
