# Generated by Django 5.2.17 on 2026-09-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_folder_name_validator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reachable', models.BooleanField(default=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_ok_at', models.DateTimeField(blank=True, null=True)),
                ('down_since', models.DateTimeField(blank=True, null=True)),
                ('alerted_down_at', models.DateTimeField(blank=True, null=True)),
                ('alerted_up_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'scanner status',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='quarantined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='scan_signature',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='scan_status',
            field=models.CharField(choices=[('unscanned', 'Not scanned'), ('clean', 'Clean'), ('infected', 'Infected'), ('error', 'Could not be scanned')], default='unscanned', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
